### ISSUE TITLE
notebook creditdefaultswap_with_rivapy.ipynb: Add image path and remove (klären)

### ISSUE THREAD

**Issue by hnguyen-RIVACON** [RIVACON/RiVaPy#81]

**Comment by maxm2301** [comment]
@hnguyen-RIVACON, weißt du noch was genau das Problem hier war?

**Comment by hnguyen-RIVACON** [comment]
Der ursprüngliche Link zum Bild war falsch referenziert.

**Comment by maxm2301** [comment]
Ich sehe da kein Bild? Wurde das schon entfernt?

**Comment by maxm2301** [comment]
In develop gefixt.
